// generated using packages/utils/scripts/gen-countries.mjs

export const COUNTRIES = [
  { countryCode: "AE", name: "United Arab Emirates" },
  { countryCode: "AF", name: "Afghanistan" },
  { countryCode: "AL", name: "Albania" },
  { countryCode: "AM", name: "Armenia" },
  { countryCode: "AO", name: "Angola" },
  { countryCode: "AQ", name: "Antarctica" },
  { countryCode: "AR", name: "Argentina" },
  { countryCode: "AT", name: "Austria" },
  { countryCode: "AU", name: "Australia" },
  { countryCode: "AZ", name: "Azerbaijan" },
  { countryCode: "BA", name: "Bosnia and Herz." },
  { countryCode: "BD", name: "Bangladesh" },
  { countryCode: "BE", name: "Belgium" },
  { countryCode: "BF", name: "Burkina Faso" },
  { countryCode: "BG", name: "Bulgaria" },
  { countryCode: "BI", name: "Burundi" },
  { countryCode: "BJ", name: "Benin" },
  { countryCode: "BN", name: "Brunei" },
  { countryCode: "BO", name: "Bolivia" },
  { countryCode: "BR", name: "Brazil" },
  { countryCode: "BS", name: "Bahamas" },
  { countryCode: "BT", name: "Bhutan" },
  { countryCode: "BW", name: "Botswana" },
  { countryCode: "BY", name: "Belarus" },
  { countryCode: "BZ", name: "Belize" },
  { countryCode: "CA", name: "Canada" },
  { countryCode: "CD", name: "Dem. Rep. Congo" },
  { countryCode: "CF", name: "Central African Rep." },
  { countryCode: "CG", name: "Congo" },
  { countryCode: "CH", name: "Switzerland" },
  { countryCode: "CI", name: "Côte d'Ivoire" },
  { countryCode: "CL", name: "Chile" },
  { countryCode: "CM", name: "Cameroon" },
  { countryCode: "CN", name: "China" },
  { countryCode: "TW", name: "Taiwan" },
  { countryCode: "CO", name: "Colombia" },
  { countryCode: "CR", name: "Costa Rica" },
  { countryCode: "CU", name: "Cuba" },
  { countryCode: "CY", name: "Cyprus" },
  { countryCode: "CZ", name: "Czechia" },
  { countryCode: "DE", name: "Germany" },
  { countryCode: "DJ", name: "Djibouti" },
  { countryCode: "DK", name: "Denmark" },
  { countryCode: "DO", name: "Dominican Rep." },
  { countryCode: "DZ", name: "Algeria" },
  { countryCode: "EC", name: "Ecuador" },
  { countryCode: "EE", name: "Estonia" },
  { countryCode: "EG", name: "Egypt" },
  { countryCode: "EH", name: "W. Sahara" },
  { countryCode: "ER", name: "Eritrea" },
  { countryCode: "ES", name: "Spain" },
  { countryCode: "ET", name: "Ethiopia" },
  { countryCode: "FI", name: "Finland" },
  { countryCode: "FJ", name: "Fiji" },
  { countryCode: "FK", name: "Falkland Is." },
  { countryCode: "FR", name: "France" },
  { countryCode: "GA", name: "Gabon" },
  { countryCode: "GE", name: "Georgia" },
  { countryCode: "GH", name: "Ghana" },
  { countryCode: "GL", name: "Greenland" },
  { countryCode: "GM", name: "Gambia" },
  { countryCode: "GN", name: "Guinea" },
  { countryCode: "GQ", name: "Eq. Guinea" },
  { countryCode: "GR", name: "Greece" },
  { countryCode: "GT", name: "Guatemala" },
  { countryCode: "GW", name: "Guinea-Bissau" },
  { countryCode: "GY", name: "Guyana" },
  { countryCode: "HN", name: "Honduras" },
  { countryCode: "HR", name: "Croatia" },
  { countryCode: "HT", name: "Haiti" },
  { countryCode: "HU", name: "Hungary" },
  { countryCode: "ID", name: "Indonesia" },
  { countryCode: "IE", name: "Ireland" },
  { countryCode: "IL", name: "Israel" },
  { countryCode: "IN", name: "India" },
  { countryCode: "IQ", name: "Iraq" },
  { countryCode: "IR", name: "Iran" },
  { countryCode: "IS", name: "Iceland" },
  { countryCode: "IT", name: "Italy" },
  { countryCode: "JM", name: "Jamaica" },
  { countryCode: "JO", name: "Jordan" },
  { countryCode: "JP", name: "Japan" },
  { countryCode: "KE", name: "Kenya" },
  { countryCode: "KG", name: "Kyrgyzstan" },
  { countryCode: "KH", name: "Cambodia" },
  { countryCode: "KP", name: "North Korea" },
  { countryCode: "KR", name: "South Korea" },
  { countryCode: "KW", name: "Kuwait" },
  { countryCode: "KZ", name: "Kazakhstan" },
  { countryCode: "LA", name: "Laos" },
  { countryCode: "LB", name: "Lebanon" },
  { countryCode: "LK", name: "Sri Lanka" },
  { countryCode: "LR", name: "Liberia" },
  { countryCode: "LS", name: "Lesotho" },
  { countryCode: "LT", name: "Lithuania" },
  { countryCode: "LU", name: "Luxembourg" },
  { countryCode: "LV", name: "Latvia" },
  { countryCode: "LY", name: "Libya" },
  { countryCode: "MA", name: "Morocco" },
  { countryCode: "MD", name: "Moldova" },
  { countryCode: "ME", name: "Montenegro" },
  { countryCode: "MG", name: "Madagascar" },
  { countryCode: "MK", name: "North Macedonia" },
  { countryCode: "ML", name: "Mali" },
  { countryCode: "MM", name: "Myanmar" },
  { countryCode: "MN", name: "Mongolia" },
  { countryCode: "MR", name: "Mauritania" },
  { countryCode: "MW", name: "Malawi" },
  { countryCode: "MX", name: "Mexico" },
  { countryCode: "MY", name: "Malaysia" },
  { countryCode: "MZ", name: "Mozambique" },
  { countryCode: "NA", name: "Namibia" },
  { countryCode: "NC", name: "New Caledonia" },
  { countryCode: "NE", name: "Niger" },
  { countryCode: "NG", name: "Nigeria" },
  { countryCode: "NI", name: "Nicaragua" },
  { countryCode: "NL", name: "Netherlands" },
  { countryCode: "NO", name: "Norway" },
  { countryCode: "NP", name: "Nepal" },
  { countryCode: "NZ", name: "New Zealand" },
  { countryCode: "OM", name: "Oman" },
  { countryCode: "PA", name: "Panama" },
  { countryCode: "PE", name: "Peru" },
  { countryCode: "PG", name: "Papua New Guinea" },
  { countryCode: "PH", name: "Philippines" },
  { countryCode: "PK", name: "Pakistan" },
  { countryCode: "PL", name: "Poland" },
  { countryCode: "PR", name: "Puerto Rico" },
  { countryCode: "PS", name: "Palestine" },
  { countryCode: "PT", name: "Portugal" },
  { countryCode: "PY", name: "Paraguay" },
  { countryCode: "QA", name: "Qatar" },
  { countryCode: "RO", name: "Romania" },
  { countryCode: "RS", name: "Serbia" },
  { countryCode: "RU", name: "Russia" },
  { countryCode: "RW", name: "Rwanda" },
  { countryCode: "SA", name: "Saudi Arabia" },
  { countryCode: "SB", name: "Solomon Is." },
  { countryCode: "SD", name: "Sudan" },
  { countryCode: "SE", name: "Sweden" },
  { countryCode: "SI", name: "Slovenia" },
  { countryCode: "SK", name: "Slovakia" },
  { countryCode: "SL", name: "Sierra Leone" },
  { countryCode: "SN", name: "Senegal" },
  { countryCode: "SO", name: "Somalia" },
  { countryCode: "SR", name: "Suriname" },
  { countryCode: "SS", name: "S. Sudan" },
  { countryCode: "SV", name: "El Salvador" },
  { countryCode: "SY", name: "Syria" },
  { countryCode: "SZ", name: "eSwatini" },
  { countryCode: "TD", name: "Chad" },
  { countryCode: "TF", name: "Fr. S. Antarctic Lands" },
  { countryCode: "TG", name: "Togo" },
  { countryCode: "TH", name: "Thailand" },
  { countryCode: "TJ", name: "Tajikistan" },
  { countryCode: "TL", name: "Timor-Leste" },
  { countryCode: "TM", name: "Turkmenistan" },
  { countryCode: "TN", name: "Tunisia" },
  { countryCode: "TR", name: "Turkey" },
  { countryCode: "TT", name: "Trinidad and Tobago" },
  { countryCode: "TZ", name: "Tanzania" },
  { countryCode: "UA", name: "Ukraine" },
  { countryCode: "UG", name: "Uganda" },
  { countryCode: "UK", name: "United Kingdom" },
  { countryCode: "US", name: "United States of America" },
  { countryCode: "UY", name: "Uruguay" },
  { countryCode: "UZ", name: "Uzbekistan" },
  { countryCode: "VE", name: "Venezuela" },
  { countryCode: "VN", name: "Vietnam" },
  { countryCode: "VU", name: "Vanuatu" },
  { countryCode: "XK", name: "Kosovo" },
  { countryCode: "YE", name: "Yemen" },
  { countryCode: "ZA", name: "South Africa" },
  { countryCode: "ZM", name: "Zambia" },
  { countryCode: "ZW", name: "Zimbabwe" },
] as const;
